ShipmentApp/ShipmentApp.Web/Models/ErrorViewModel.cs
using System;

namespace ShipmentApp.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ShipmentApp/ShipmentApp.Web/Controllers/CarrierController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ShipmentApp.Domain.Contracts;
using ShipmentApp.Domain.Contracts.ViewModels;
using Swashbuckle.AspNetCore.Annotations;

namespace ShipmentApp.Web.Controllers
{
    [Route("carrier")]
    public class CarrierController : Controller
    {
        private readonly ICarrierService carrierService;

        public CarrierController(ICarrierService carrierService)
        {
            this.carrierService = carrierService;
        }

        [HttpGet("index")]
        [ApiExplorerSettings(IgnoreApi = true)]
        public IActionResult Index()
        {
            return View();
        }

        [SwaggerOperation(Summary = "Create/Update carrier, returns status code")]
        [HttpPost("create")]
        public IActionResult Create(CarrierViewModel viewModel)
        {
            if (viewModel.Id == 0)
            {
                carrierService.Create(viewModel);
            }
            else
            {
                carrierService.Update(viewModel);
            }

            return Ok();
        }

        [SwaggerOperation(Summary = "Delete carrier, returns status code")]
        [HttpGet("delete")]
        public IActionResult Delete(int id)
        {
            carrierService.Delete(id);
            return Ok();
        }

        [SwaggerOperation(Summary = "Returns all carriers in JSON format")]
        [HttpGet("getall")]
        public JsonResult GetAll()
        {
            var carriers = carrierService.GetAll();
            return Json(carriers);
        }
    }
}

ShipmentApp/ShipmentApp.Web/Controllers/ShipmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.OData;
using Microsoft.AspNetCore.Mvc;
using ShipmentApp.Domain.Contracts;
using ShipmentApp.Domain.Contracts.ViewModels;
using Swashbuckle.AspNetCore.Annotations;

namespace ShipmentApp.Web.Controllers
{
    [Route("shipment")]
    public class ShipmentController : Controller
    {
        private readonly IShipmentService shipmentService;

        public ShipmentController(IShipmentService shipmentService)
        {
            this.shipmentService = shipmentService;
        }

        [ApiExplorerSettings(IgnoreApi = true)]
        [HttpGet("index")]
        public IActionResult Index()
        {
            return View();
        }

        [ApiExplorerSettings(IgnoreApi = true)]
        [HttpGet("create")]
        [HttpGet("create/{id:guid}")]
        public IActionResult Create(Guid? id)
        {
            if (id == null)
            {
                return View();
            }
                
            var shipments = shipmentService.Retrieve(id.Value);
            return View(shipments);
        }

        [ApiExplorerSettings(IgnoreApi = true)]
        [HttpPost("create")]
        public IActionResult Create(ShipmentViewModel viewModel)
        {
            if (viewModel.Id == new Guid())
            {
                shipmentService.Create(viewModel);
            }
            else
            {
                shipmentService.Update(viewModel);
            }

            return RedirectToAction("Index");
        }

        [ApiExplorerSettings(IgnoreApi = true)]
        [HttpGet("retrieve/{id:guid}")]
        public IActionResult Retrieve(Guid id)
        {
            var shipment = shipmentService.Retrieve(id);
            return View(shipment);
        }

        [ApiExplorerSettings(IgnoreApi = true)]
        [HttpGet("delete")]
        public IActionResult Delete(Guid id)
        {
            shipmentService.Delete(id);
            return RedirectToAction("Index");
        }

        [SwaggerOperation(Summary = "Returns all shipments in JSON format")]
        [HttpGet("getall")]
        [EnableQuery()]
        public ActionResult<IQueryable<ShipmentViewModel>> GetAll()
        {
            var shipments = new ActionResult<IQueryable<ShipmentViewModel>>(shipmentService.RetrieveAll());
            return shipments;
        }
    }
}

ShipmentApp/ShipmentApp.Web/Views/Carrier/Index.cshtml
<a asp-controller="Shipment" asp-action="Index">Back to grid</a>

<br />
<hr />
<br />

<div id="gridCarriers"></div>

<script>
    $(document).ready(function () {
        var dataSourceqq = new kendo.data.DataSource({
            transport: {
                read: {
                    dataType: "json",
                    url: "https://localhost:44399/carrier/getall"
                },
                create: {
                    url: "https://localhost:44399/carrier/create",
                    type: "POST"
                },
                update: {
                    url: "https://localhost:44399/carrier/create",
                    type: "POST"
                },
                destroy: {
                    url: "https://localhost:44399/carrier/delete",
                    type: "GET"
                }
            },
            batch: false,
            schema: {
                model: {
                    id: "id",
                    fields: {
                        id: {
                            editable: false,
                            nullable: false
                        },
                        name: {
                            type: "string",
                            validation: { required: true }
                        },
                        numberOfShipments: {
                            editable: false,
                            type: "number"
                        }
                    }
                }
            }
        });

        $("#gridCarriers").kendoGrid({
            dataSource: dataSourceqq,
            height: 550,
            sortable: true,
            pageable: true,
            toolbar: ["create"],
            columns: [
                {
                    field: "name",
                    title: "Carrier name"
                },
                {
                    field: "numberOfShipments",
                    title: "Number of shipments"
                },
                { command: ["edit", "destroy"] }
            ],
            editable: "inline"
        });
    });
</script>

ShipmentApp/ShipmentApp.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ShipmentApp/ShipmentApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShipmentApp.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>

    <link rel="stylesheet" href="~/css/kendo.common.min.css" />
    <link rel="stylesheet" href="~/css/kendo.default.min.css" />
    <link rel="stylesheet" href="~/css/kendo.default.mobile.min.css" />

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/js/kendo.all.min.js"></script>
    <script src="~/grid.js"></script>
    <script src="~/dropdown.js"></script>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ShipmentApp.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - ShipmentApp.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        @*<script src="~/lib/jquery/dist/jquery.js"></script>*@
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

ShipmentApp/ShipmentApp.Web/Views/Shipment/Create.cshtml
@model ShipmentApp.Domain.Contracts.ViewModels.ShipmentViewModel

    <form asp-action="Create">
        <div class="form-group">
            <label asp-for="Description" class="control-label"></label>
            <input asp-for="Description" class="form-control" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="SenderName" class="control-label"></label>
            <input asp-for="SenderName" class="form-control" />
            <span asp-validation-for="SenderName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="RecipientName" class="control-label"></label>
            <input asp-for="RecipientName" class="form-control" />
            <span asp-validation-for="RecipientName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Weight" class="control-label"></label>
            <input asp-for="Weight" type="number" class="form-control" />
            <span asp-validation-for="Weight" class="text-danger"></span>
        </div>
        <br />
        <br />
        <div class="form-group">
            <label asp-for="CarrierName" class="control-label"></label>
            <input asp-for="CarrierId" id="products" />
            <span asp-validation-for="Weight" class="text-danger"></span>
        </div>
        <br />
        <br />
        <div class="row justify-content-between">
            <div class="col-5">
                <h4>Sender Address</h4>
                <br />
                <div class="form-group">
                    <label asp-for="SenderAddress.PostCode" class="control-label"></label>
                    <input asp-for="SenderAddress.PostCode" class="form-control" />
                    <span asp-validation-for="SenderAddress.PostCode" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SenderAddress.CountryCode" class="control-label"></label>
                    <input asp-for="SenderAddress.CountryCode" maxlength="2" class="form-control" />
                    <span asp-validation-for="SenderAddress.CountryCode" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SenderAddress.State" class="control-label"></label>
                    <input asp-for="SenderAddress.State" class="form-control" />
                    <span asp-validation-for="SenderAddress.State" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SenderAddress.City" class="control-label"></label>
                    <input asp-for="SenderAddress.City" class="form-control" />
                    <span asp-validation-for="SenderAddress.City" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SenderAddress.Line1" class="control-label"></label>
                    <input asp-for="SenderAddress.Line1" class="form-control" />
                    <span asp-validation-for="SenderAddress.Line1" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SenderAddress.Line2" class="control-label"></label>
                    <input asp-for="SenderAddress.Line2" class="form-control" />
                    <span asp-validation-for="SenderAddress.Line2" class="text-danger"></span>
                </div>
            </div>
            <div class="col-5">
                <h4>Recipient Address</h4>
                <br />
                <div class="form-group">
                    <label asp-for="RecipientAddress.PostCode" class="control-label"></label>
                    <input asp-for="RecipientAddress.PostCode" class="form-control" />
                    <span asp-validation-for="RecipientAddress.PostCode" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="RecipientAddress.CountryCode" class="control-label"></label>
                    <input asp-for="RecipientAddress.CountryCode" maxlength="2" class="form-control" />
                    <span asp-validation-for="RecipientAddress.CountryCode" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="RecipientAddress.State" class="control-label"></label>
                    <input asp-for="RecipientAddress.State" class="form-control" />
                    <span asp-validation-for="RecipientAddress.State" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="RecipientAddress.City" class="control-label"></label>
                    <input asp-for="RecipientAddress.City" class="form-control" />
                    <span asp-validation-for="RecipientAddress.City" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="RecipientAddress.Line1" class="control-label"></label>
                    <input asp-for="RecipientAddress.Line1" class="form-control" />
                    <span asp-validation-for="RecipientAddress.Line1" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="RecipientAddress.Line2" class="control-label"></label>
                    <input asp-for="RecipientAddress.Line2" class="form-control" />
                    <span asp-validation-for="RecipientAddress.Line2" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="form-group">
            @if (Model != null)
            {
                <input type="submit" value="Update" class="btn btn-primary" />
            }
            else
            {
                <input type="submit" value="Create" class="btn btn-primary" />
            }
        </div>
    </form>

ShipmentApp/ShipmentApp.Web/Views/Shipment/Index.cshtml
<div class="row justify-content-between">
    <div class="col-4" style="text-align:left">
        <a asp-action="Create">Add Shipment</a>
    </div>
    <div class="col-4" style="text-align:right">
        <a asp-controller="Carrier" asp-action="Index">All Carriers</a>
    </div>
</div>

<br />
<hr />
<br />

<div id="grid"></div>

ShipmentApp/ShipmentApp.Web/Views/Shipment/Retrieve.cshtml
@model ShipmentApp.Domain.Contracts.ViewModels.ShipmentViewModel

<h1>Retrieve</h1>

<dl class="row">
    <dt class="col-2">
        Description
    </dt>
    <dd class="col-10">
        @Model.Description
    </dd>
    <dt class="col-2">
        Weight
    </dt>
    <dd class="col-10">
        @Model.Weight
    </dd>
</dl>

<br />
<hr />
<br />
<br />
<dl class="row">
    <dt class="col-2">
        Carrier name
    </dt>
    <dd class="col-10">
        @Model.CarrierName
    </dd>
</dl>
<br />
<hr />
<br />
<br />

<div class="row justify-content-between">
    <div class="col-5">
        <dl class="row">
            <dt class="col-2">
                Sender Name
            </dt>
            <dd class="col-10">
                @Model.SenderName
            </dd>
            <dt class="col-2">
                Post Code
            </dt>
            <dd class="col-10">
                @Model.SenderAddress.PostCode
            </dd>
            <dt class="col-2">
                Country Code
            </dt>
            <dd class="col-10">
                @Model.SenderAddress.CountryCode
            </dd>
            <dt class="col-2">
                State
            </dt>
            <dd class="col-10">
                @Model.SenderAddress.State
            </dd>
            <dt class="col-2">
                City
            </dt>
            <dd class="col-10">
                @Model.SenderAddress.City
            </dd>
            <dt class="col-2">
                Line1
            </dt>
            <dd class="col-10">
                @Model.SenderAddress.Line1
            </dd>
            <dt class="col-2">
                Line2
            </dt>
            <dd class="col-10">
                @Model.SenderAddress.Line2
            </dd>
        </dl>
    </div>
    <div class="col-5">
        <dl class="row">
            <dt class="col-2">
                Recipient Name
            </dt>
            <dd class="col-10">
                @Model.RecipientName
            </dd>
            <dt class="col-2">
                Post Code
            </dt>
            <dd class="col-10">
                @Model.RecipientAddress.PostCode
            </dd>
            <dt class="col-2">
                Country Code
            </dt>
            <dd class="col-10">
                @Model.RecipientAddress.CountryCode
            </dd>
            <dt class="col-2">
                State
            </dt>
            <dd class="col-10">
                @Model.RecipientAddress.State
            </dd>
            <dt class="col-2">
                City
            </dt>
            <dd class="col-10">
                @Model.RecipientAddress.City
            </dd>
            <dt class="col-2">
                Line1
            </dt>
            <dd class="col-10">
                @Model.RecipientAddress.Line1
            </dd>
            <dt class="col-2">
                Line2
            </dt>
            <dd class="col-10">
                @Model.RecipientAddress.Line2
            </dd>
        </dl>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
    <br />
    <a asp-action="Create" asp-route-id="@Model.Id">Update</a>
    <br />
    <a asp-action="Delete" asp-route-id="@Model.Id">Delete </a>
</div>